### ISSUE TITLE
The excursions such as temperature, humidity delay etc related to a shipment should also have details( for eg excursion type)  added along with the boolean flag

### ISSUE THREAD

**Issue by komal-joshi-kiwitech** [TransparentPath/buildly-core#23]
Currently We only have flag set in shipment api for any excursion. Other than that there is no way to specify what kind of excursion it is.
- [ ] Add excursion_flag boolen for temperature  
- [ ] Add excursion_flag boolen for humidity

**Comment by yasmin2496** [comment]
@glind Here, we saw that shipments are mapped to sensors like temperature, battery level. Are we referring to these sensors as excursions or is there some other place we need to look into?

**Comment by glind** [comment]
Yes, an excursion happens when a temperature reading or a humidity reading goes outside the user defined boundaries in the shipment endpoint.

`

max_excursion_temp | numbertitle: Max excursion tempMaximum Temperature before Excursion Flag
-- | --
min_excursion_temp | numbertitle: Min excursion tempMinimum Temperature before Excursion Flag
max_warning_humidity | numbertitle: Max warning humidityHigh Humidity warning threshold
min_warning_humidity | number
`

**Comment by yasmin2496** [comment]
Okay got it. 👍

**Comment by vishalajackus** [comment]
@glind As this issue is linked with buildly-core, but this issue seems to be for shipment service.
So I have created the same issue and linked with the shipment service.
Its link is https://github.com/TransparentPath/shipment_service/issues/6.
Shall I close this issue?

**Comment by glind** [comment]
@vishalajackus That's fine, if you don't mind copy in the comment above from Yasmin and my response so we can track that first, then delete this issue.

**Comment by vishalajackus** [comment]
This issue recreated to link with shipment service. Its link is https://github.com/TransparentPath/shipment_service/issues/6.
